### PR TITLE
Stop project returning to draft state if content unchanged

### PR DESCRIPTION
**Pull request by jacobwindsor**
Relates to [this PR in UI](https://github.com/ebi-ait/ingest-ui/pull/79) and [this task](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/154).

I think this is the right way to do it but not 100%. I tested on local but will be better to test on dev with a few projects that are in non-draft state.

### CODE REVIEW

**Review by aaclan-ebi — APPROVED** [review]
I believe we need to also do this for other metadata.

**Comment by prabh-t** [comment]
I thought we discussed that PATCH updates are to be restricted to content updates only - see [this ticket](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/109)? So a state transition to DRAFT should only happen only when updating the content field, for all metadata document, not just project.

**Comment by aaclan-ebi** [comment]
>  PATCH updates are to be restricted to content updates only

I couldn’t restrict it to content updates only :disappointed:  some fields outside content are being updated via PATCH from other components and would affect other areas, i needed to allow the filename in files, other fields for the project, validationErrors and maybe some more fields 

> So a state transition to DRAFT should only happen only when updating the content field, for all metadata document, not just project.
yup, this is correct

**Review by jacobwindsor — COMMENTED** [review]
Great! Thanks @aaclan-ebi and particularly thanks for adding the test.

**Comment by jacobwindsor** [comment]
@aaclan-ebi 52db96e186031722bc80d41564f7cf780399c5c7 is stopping @mshadbolt progressing with adding organs to the project. Just so you're both aware what the blocker is

**Review by prabh-t — APPROVED** [review]
Looks good pulling the patch/update logic for all entities in one place.

**Pull request merged**
