### PR TITLE
Only transition to pending if not already in pending

### PR DESCRIPTION
**Pull request by jacobwindsor**
Fixes a bug that @ami-day found.

Not really a bug, it just causes an error to be reported in the UI when there isn't one

### CODE REVIEW

**Review by aaclan-ebi — APPROVED** [review]

**Review by ke4 — COMMENTED** [review]
Can we replicate the original issue with a unit test?

**Comment by jacobwindsor** [comment]
@ke4 it's not really an issue, just that the service will raise a RuntimeException when requesting PENDING->PENDING, which will then be reported in the UI. It doesn't block anything

**Review by aaclan-ebi — APPROVED** [review]

**Review by aaclan-ebi — APPROVED** [review]

**Comment by aaclan-ebi** [comment]
You could actually add a unit test for the performGraphRequest function that could test that if the submission is still pending it shouldn't do handleGraphValidation

**Comment by jacobwindsor** [comment]
@aaclan-ebi performGraphRequest is a private function

**Comment by aaclan-ebi** [comment]
I see, then i think if it's covered in the integration test, it's fine.

**Review by ke4 — APPROVED** [review]

**Review by amnonkhen — COMMENTED** [review]
@jacobwindsor can you add some info about the bug, and possibly a test?

**Comment by jacobwindsor** [comment]
This is stale after dcp-456 so closing

**Pull request closed without merging**
